library(dplyr)
library(lubridate)
library(tidyr)

data <- tbl_df(read.csv("household_power_consumption.txt", sep = ";", header = TRUE))
data <- mutate(data, datetime = dmy(Date) + hms(Time))
data <- filter(data, Global_active_power != "?")
data <- filter(data, datetime >= ymd("2007-02-01"), datetime < ymd("2007-02-03"))
data <- mutate(data, Global_active_power = as.numeric(as.character(Global_active_power)))
data <- mutate(data, Global_reactive_power = as.numeric(as.character(Global_reactive_power)))
data <- mutate(data, Voltage = as.numeric(as.character(Voltage)))
data <- mutate(data, Global_intensity = as.numeric(as.character(Global_intensity)))
data <- mutate(data, Sub_metering_1 = as.numeric(as.character(Sub_metering_1)))
data <- mutate(data, Sub_metering_2 = as.numeric(as.character(Sub_metering_2)))
data <- mutate(data, Sub_metering_3 = as.numeric(as.character(Sub_metering_3)))

png(filename = "plot1.png", width = 480, height = 480, bg="transparent")
hist(data$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red")
dev.off()